# Generated by Django 4.1.5 on 2023-02-12 13:58

from django.db import migrations, models
import user_app.models
import user_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, default='banner.jpg', upload_to=user_app.models.user_directory_path, validators=[user_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='ava.jpg', upload_to=user_app.models.user_directory_path, validators=[user_app.validators.validate_file_size]),
        ),
    ]
