# Generated by Django 4.1.5 on 2023-02-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='dark',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
