# Generated by Django 4.1.5 on 2023-02-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_theme_dark'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(blank=True, choices=[('L', 'Light'), ('D', 'Dark')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
