# Generated by Django 4.1.5 on 2023-02-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_profile_theme_delete_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
    ]
